import { Product, Brand, Collection } from './types';

export const BRANDS: Brand[] = [
  { id: 1, name: "Heein Signature" },
  { id: 2, name: "Maison de Luxe" },
  { id: 3, name: "Aqua di Mare" },
  { id: 4, name: "Arabian Oud" },
  { id: 5, name: "Desert Gems" },
  { id: 6, name: "Carolina Herrera" },
  { id: 7, name: "O Boticário" },
  { id: 8, name: "Lattafa" },
  { id: 9, name: "Azzaro" },
  { id: 10, name: "Chanel" },
  { id: 11, name: "Calvin Klein" },
  { id: 12, name: "Dolce & Gabbana" },
  { id: 13, name: "Xerjoff" },
  { id: 14, name: "Natura" },
  { id: 15, name: "Paco Rabanne" },
  { id: 16, name: "Ferrari" },
  { id: 17, name: "Gabriela Sabatini" },
  { id: 18, name: "Issey Miyake" },
  { id: 19, name: "Dior" },
  { id: 20, name: "Lancôme" },
  { id: 21, name: "Lacoste" },
  { id: 22, name: "Ralph Lauren" },
  { id: 23, name: "Giorgio Armani" },
  { id: 24, name: "Jacques Bogart" },
  { id: 25, name: "Ted Lapidus" },
  { id: 26, name: "Yves Saint Laurent" },
];

export const COLLECTIONS: Collection[] = [
  { 
    id: "colecao_arabe", 
    name: "Coleção Árabe", 
    description: "Perfumes inspirados na alta perfumaria árabe, com essências ricas, intensas e misteriosas que representam o verdadeiro luxo do Oriente." 
  },
];


export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: "noir-ambre",
    name: "Noir Ambré",
    brand: "Heein Signature",
    category: "Amadeirado",
    gender: "Masculino",
    price: 80,
    notes: ["Âmbar", "Rosa", "Bergamota", "Sândalo"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Uma fragrância intensa e misteriosa, Noir Ambré combina a riqueza do âmbar com a delicadeza da rosa e o frescor da bergamota, sobre uma base cremosa de sândalo. Perfeito para noites inesquecíveis."
  },
  {
    id: 2,
    slug: "aurora-citrus",
    name: "Aurora Citrus",
    brand: "Heein Signature",
    category: "Cítrico",
    gender: "Unissex",
    price: 80,
    notes: ["Limão Siciliano", "Jasmim", "Neroli"],
    rating: 4.7,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Vibrante e luminoso, Aurora Citrus é uma explosão de frescor. As notas de limão siciliano se entrelaçam com a elegância do jasmim e a suavidade do neroli, evocando um amanhecer radiante."
  },
  {
    id: 3,
    slug: "vanille-royale",
    name: "Vanille Royale",
    brand: "Maison de Luxe",
    category: "Doce",
    gender: "Feminino",
    price: 80,
    notes: ["Baunilha de Madagascar", "Fava Tonka", "Orquídea"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Opulento e cativante, Vanille Royale é uma homenagem à baunilha mais pura. Com toques de fava tonka e orquídea, esta fragrância é um convite a um mundo de luxo e sofisticação."
  },
  {
    id: 4,
    slug: "ocean-breeze",
    name: "Ocean Breeze",
    brand: "Aqua di Mare",
    category: "Fresco",
    gender: "Unissex",
    price: 80,
    notes: ["Notas Marinhas", "Lavanda", "Alecrim"],
    rating: 4.6,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Sinta a brisa do oceano com esta fragrância revigorante. Notas marinhas se unem à lavanda e ao alecrim para criar uma sensação de liberdade e pureza, ideal para o dia a dia."
  },
  {
    id: 5,
    slug: "oud-imperial",
    name: "Oud Imperial",
    brand: "Arabian Oud",
    category: "Amadeirado",
    gender: "Masculino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Oud", "Açafrão", "Sândalo"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Uma jornada olfativa ao coração do Oriente. Oud Imperial combina a nobreza do Oud com o calor do açafrão e a cremosidade do sândalo, para uma fragrância inesquecível e poderosa."
  },
  {
    id: 6,
    slug: "desert-rose",
    name: "Desert Rose",
    brand: "Desert Gems",
    category: "Floral",
    gender: "Feminino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Rosa de Taif", "Âmbar", "Frutas Vermelhas"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Como uma flor rara no deserto, esta fragrância combina a delicadeza da Rosa de Taif com a doçura das frutas vermelhas e a base quente do âmbar."
  },
  {
    id: 7,
    slug: "amber-sultan",
    name: "Amber Sultan",
    brand: "Arabian Oud",
    category: "Oriental",
    gender: "Unissex",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Âmbar Negro", "Baunilha", "Incenso"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Intenso e majestoso, Amber Sultan é uma ode ao âmbar negro. Uma fragrância opulenta e resinosa, com toques de baunilha e incenso."
  },
  {
    id: 8,
    slug: "saffron-kiss",
    name: "Saffron Kiss",
    brand: "Desert Gems",
    category: "Especiado",
    gender: "Unissex",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Açafrão", "Couro", "Framboesa"],
    rating: 4.7,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Um perfume audacioso e sensual. O calor do açafrão encontra a suavidade do couro e um toque surpreendente de framboesa."
  },
  {
    id: 9,
    slug: "ruby-elixir",
    name: "Ruby Elixir",
    brand: "Desert Gems",
    category: "Frutado",
    gender: "Feminino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Frutas Vermelhas", "Rosa", "Almíscar"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Um elixir viciante de frutas vermelhas suculentas, envolvidas pela feminilidade da rosa e a sensualidade do almíscar branco."
  },
  {
    id: 10,
    slug: "sandalwood-majesty",
    name: "Sandalwood Majesty",
    brand: "Arabian Oud",
    category: "Amadeirado",
    gender: "Masculino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Sândalo Mysore", "Cardamomo", "Oud"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "A cremosidade do Sândalo de Mysore em sua forma mais nobre. Uma fragrância elegante, especiada com cardamomo e um toque sutil de Oud."
  },
  {
    id: 11,
    slug: "vanilla-oasis",
    name: "Vanilla Oasis",
    brand: "Desert Gems",
    category: "Doce",
    gender: "Unissex",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Baunilha Absoluta", "Âmbar", "Fava Tonka"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Um oásis de doçura no deserto. Baunilha cremosa e envolvente, aquecida pelo âmbar e pela fava tonka, criando um rastro inesquecível."
  },
  {
    id: 12,
    slug: "midnight-oud",
    name: "Midnight Oud",
    brand: "Arabian Oud",
    category: "Intenso",
    gender: "Masculino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Oud Cambojano", "Rosa Negra", "Patchouli"],
    rating: 5.0,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Misterioso e profundo como a noite no deserto. O mais puro Oud Cambojano se une à sedutora rosa negra e ao terroso patchouli."
  },
  {
    id: 13,
    slug: "crimson-silk",
    name: "Crimson Silk",
    brand: "Desert Gems",
    category: "Floral",
    gender: "Feminino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Rosa Búlgara", "Açafrão", "Lichia"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Macio como seda carmesim, este perfume é um tributo à rosa búlgara, com o toque exótico do açafrão e a suculência da lichia."
  },
  {
    id: 14,
    slug: "golden-emir",
    name: "Golden Emir",
    brand: "Arabian Oud",
    category: "Oriental",
    gender: "Masculino",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Âmbar", "Mel", "Tabaco"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Rico e opulento como o ouro de um emir. Uma combinação luxuosa de âmbar dourado, mel e folhas de tabaco."
  },
  {
    id: 15,
    slug: "mystic-aoud",
    name: "Mystic Aoud",
    brand: "Desert Gems",
    category: "Amadeirado",
    gender: "Unissex",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Oud", "Mirra", "Incenso"],
    rating: 4.8,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Uma fragrância mística e espiritual. A fumaça sagrada do incenso e da mirra se entrelaçam com a profundidade do Oud."
  },
  {
    id: 16,
    slug: "saharan-treasure",
    name: "Saharan Treasure",
    brand: "Arabian Oud",
    category: "Especiado",
    gender: "Unissex",
    collection: "colecao_arabe",
    price: 80,
    notes: ["Especiarias", "Tâmaras", "Sândalo"],
    rating: 4.9,
    image: "https://i.imgur.com/WDpriz2.jpeg",
    description: "Um tesouro escondido nas areias do Saara. Uma mistura quente de especiarias orientais, a doçura das tâmaras e a base cremosa do sândalo."
  },
  { id: 17, slug: "212-masculino-tradicional", name: "212 Masculino Tradicional", brand: "Carolina Herrera", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Folhas cítricas", "Gengibre", "Sândalo"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Fragrância moderna e inovadora, para o homem dinâmico e urbano." },
  { id: 18, slug: "212-vip-club-man", name: "212 VIP Club Man", brand: "Carolina Herrera", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Gelo", "Caviar de lima", "Pimenta preta"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para o homem com espírito noturno, magnético e sedutor." },
  { id: 19, slug: "212-vip-rose", name: "212 VIP Rosé", brand: "Carolina Herrera", gender: "Feminino", category: "Floral", price: 80, notes: ["Champagne rosé", "Flor de pêssego", "Almíscar branco"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um floral frutado que exala feminilidade e glamour." },
  { id: 20, slug: "arbo", name: "Arbo", brand: "O Boticário", gender: "Masculino", category: "Fougère", price: 80, notes: ["Folha de laranjeira", "Gerânio", "Musk"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Fragrância que remete ao frescor da natureza e à brisa da montanha." },
  { id: 21, slug: "asad", name: "Asad", brand: "Lattafa", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Pimenta preta", "Abacaxi", "Patchouli"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um perfume especiado e amadeirado com um toque oriental." },
  { id: 22, slug: "azzaro-pour-homme", name: "Azzaro Pour Homme", brand: "Azzaro", gender: "Masculino", category: "Fougère", price: 80, notes: ["Anis estrelado", "Lavanda", "Couro"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um clássico atemporal da perfumaria masculina, sinônimo de sedução." },
  { id: 23, slug: "bleu-de-chanel", name: "Bleu de Chanel", brand: "Chanel", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Cítricos", "Gengibre", "Incenso"], rating: 5, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Elegante e sofisticado, para o homem que desafia as convenções." },
  { id: 24, slug: "calvin-klein-masculino", name: "Calvin Klein Masculino", brand: "Calvin Klein", gender: "Masculino", category: "Cítrico", price: 80, notes: ["Bergamota", "Cardamomo", "Almíscar"], rating: 4.5, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância clássica, fresca e energética." },
  { id: 25, slug: "calvin-klein-one", name: "Calvin Klein One", brand: "Calvin Klein", gender: "Unissex", category: "Cítrico", price: 80, notes: ["Chá verde", "Bergamota", "Violeta"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "O perfume icônico que celebra a individualidade e a união." },
  { id: 26, slug: "coffee-man", name: "Coffee Man", brand: "O Boticário", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Café", "Couro", "Âmbar"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Inspirado na cultura do café, para homens elegantes e contemporâneos." },
  { id: 27, slug: "dolce-gabbana-feminino", name: "Dolce & Gabbana Feminino", brand: "Dolce & Gabbana", gender: "Feminino", category: "Floral", price: 80, notes: ["Tangerina", "Jasmim", "Baunilha"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância clássica e feminina, com um toque mediterrâneo." },
  { id: 28, slug: "egeo-tradicional-masculino", name: "Egeo Tradicional Masculino", brand: "O Boticário", gender: "Masculino", category: "Doce", price: 80, notes: ["Chocolate", "Baunilha", "Madeiras"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma combinação irresistível para quem gosta de fragrâncias doces." },
  { id: 29, slug: "elysee-feminino", name: "Elysée Feminino", brand: "O Boticário", gender: "Feminino", category: "Floral", price: 80, notes: ["Mandarina", "Rosa", "Patchouli"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância marcante e sofisticada para a mulher que sabe o que quer." },
  { id: 30, slug: "erba-gold", name: "Erba Gold", brand: "Xerjoff", gender: "Feminino", category: "Frutado", price: 80, notes: ["Frutas tropicais", "Âmbar", "Almíscar"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma explosão de frutas exóticas sobre uma base quente e sensual." },
  { id: 31, slug: "erba-pura", name: "Erba Pura", brand: "Xerjoff", gender: "Masculino", category: "Âmbar", price: 80, notes: ["Laranja", "Limão", "Baunilha"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um perfume moderno e cativante com um coração frutado e base ambarada." },
  { id: 32, slug: "essencial-masculino", name: "Essencial Masculino", brand: "Natura", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Madeiras nobres", "Especiarias", "Copaíba"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para o homem que é protagonista de sua vida." },
  { id: 33, slug: "fame", name: "Fame", brand: "Paco Rabanne", gender: "Feminino", category: "Floral", price: 80, notes: ["Manga", "Jasmim", "Incenso"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "O novo ícone feminino, que captura o espírito parisiense." },
  { id: 34, slug: "ferrari-black", name: "Ferrari Black", brand: "Ferrari", gender: "Masculino", category: "Fougère", price: 80, notes: ["Maçã vermelha", "Canela", "Cedro"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um perfume misterioso e sensual para o homem moderno." },
  { id: 35, slug: "floratta-gold", name: "Floratta Gold", brand: "O Boticário", gender: "Feminino", category: "Floral", price: 80, notes: ["Orquídea", "Baunilha", "Sândalo"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância que combina o glamour do ouro com a delicadeza das flores." },
  { id: 36, slug: "gabriela-sabatini", name: "Gabriela Sabatini", brand: "Gabriela Sabatini", gender: "Feminino", category: "Floral", price: 80, notes: ["Tangerina", "Jasmim", "Musgo de carvalho"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um clássico da perfumaria, para a mulher autêntica e decidida." },
  { id: 37, slug: "her-code", name: "Her Code", brand: "O Boticário", gender: "Feminino", category: "Floral", price: 80, notes: ["Frutas vermelhas", "Jasmim", "Prisma de açúcar"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância que te incentiva a descobrir seu próprio prazer." },
  { id: 38, slug: "invictus", name: "Invictus", brand: "Paco Rabanne", gender: "Masculino", category: "Aquático", price: 80, notes: ["Grapefruit", "Folha de louro", "Madeira guaiac"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "O perfume da vitória, para o herói invencível." },
  { id: 39, slug: "issey-miyake-leau-dissey", name: "L’Eau d’Issey", brand: "Issey Miyake", gender: "Masculino", category: "Aquático", price: 80, notes: ["Yuzu", "Canela", "Sândalo"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma cascata de frescor atemporal com um toque amadeirado." },
  { id: 40, slug: "jadore", name: "J’adore", brand: "Dior", gender: "Feminino", category: "Floral", price: 80, notes: ["Ylang-ylang", "Rosa damascena", "Jasmim"], rating: 5, image: "https://i.imgur.com/WDpriz2.jpeg", description: "O buquê floral icônico da Dior, um tributo à feminilidade." },
  { id: 41, slug: "kaiak-aventura", name: "Kaiak Aventura", brand: "Natura", gender: "Masculino", category: "Fougère", price: 80, notes: ["Notas aquosas", "Mandarina", "Musk"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para o homem que busca a aventura e o contato com a natureza." },
  { id: 42, slug: "kaiak-tradicional", name: "Kaiak Tradicional", brand: "Natura", gender: "Masculino", category: "Fougère", price: 80, notes: ["Bergamota", "Manjericão", "Musgo de carvalho"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um clássico que combina o frescor cítrico com a força das madeiras." },
  { id: 43, slug: "king-bahrara", name: "King Bahrara", brand: "Lattafa", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Âmbar", "Especiarias", "Oud"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância real e imponente, com um toque especiado e ambarado." },
  { id: 44, slug: "lacoste-masculino", name: "Lacoste Masculino", brand: "Lacoste", gender: "Masculino", category: "Cítrico", price: 80, notes: ["Toranja", "Cardamomo", "Cedro"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Elegância e frescor para o homem casual e moderno." },
  { id: 45, slug: "la-vie-est-belle", name: "La Vie Est Belle", brand: "Lancôme", gender: "Feminino", category: "Floral", price: 80, notes: ["Íris", "Jasmim", "Pralinê"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um convite à felicidade, com um toque gourmand irresistível." },
  { id: 46, slug: "lady-million", name: "Lady Million", brand: "Paco Rabanne", gender: "Feminino", category: "Floral", price: 80, notes: ["Néroli", "Framboesa", "Mel branco"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para a mulher glamourosa, audaciosa e excessiva." },
  { id: 47, slug: "lily", name: "Lily", brand: "O Boticário", gender: "Feminino", category: "Floral", price: 80, notes: ["Lírio", "Gardênia", "Sândalo"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "A sofisticação do lírio em uma fragrância inesquecível e marcante." },
  { id: 48, slug: "mademoiselle", name: "Mademoiselle", brand: "Chanel", gender: "Feminino", category: "Floral", price: 80, notes: ["Laranja", "Rosa", "Patchouli"], rating: 5, image: "https://i.imgur.com/WDpriz2.jpeg", description: "A essência de uma mulher livre e audaciosa, um oriental fresco e sensual." },
  { id: 49, slug: "malbec-gold", name: "Malbec Gold", brand: "O Boticário", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Ouro", "Madeiras", "Âmbar"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância quente e intensa que aumenta o poder de atração." },
  { id: 50, slug: "olympea", name: "Olympea", brand: "Paco Rabanne", gender: "Feminino", category: "Floral", price: 80, notes: ["Baunilha salgada", "Jasmim aquático", "Âmbar cinza"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "A deusa moderna, uma fragrância oriental fresca e poderosa." },
  { id: 51, slug: "one-million", name: "One Million", brand: "Paco Rabanne", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Mandarina", "Canela", "Couro"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "O perfume do sucesso, para o homem que sabe o que quer." },
  { id: 52, slug: "phantom", name: "Phantom", brand: "Paco Rabanne", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Lavanda", "Limão", "Baunilha"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "A essência futurista da autoconfiança, impulsionada pela energia do bem." },
  { id: 53, slug: "polo", name: "Polo", brand: "Ralph Lauren", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Pinho", "Couro", "Tabaco"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um clássico da perfumaria, para o homem de estilo e tradição." },
  { id: 54, slug: "quasar", name: "Quasar", brand: "O Boticário", gender: "Masculino", category: "Fougère", price: 80, notes: ["Limão", "Lavanda", "Sândalo"], rating: 4.6, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma explosão de energia e vitalidade para o homem que vive intensamente." },
  { id: 55, slug: "sauvage-dior", name: "Sauvage Dior", brand: "Dior", gender: "Masculino", category: "Fougère", price: 80, notes: ["Bergamota da Calábria", "Pimenta de Szechuan", "Ambroxan"], rating: 5, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma composição radicalmente fresca, para um homem autêntico e selvagem." },
  { id: 56, slug: "si-giorgio-armani", name: "Si", brand: "Giorgio Armani", gender: "Feminino", category: "Floral", price: 80, notes: ["Cassis", "Rosa de Maio", "Baunilha"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para a mulher moderna que diz 'sim' à vida, à força e aos sonhos." },
  { id: 57, slug: "silver-scent-intense", name: "Silver Scent Intense", brand: "Jacques Bogart", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Laranja amarga", "Fava Tonka", "Madeira de Oud"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma versão mais intensa e marcante do clássico Silver Scent." },
  { id: 58, slug: "silver-scent", name: "Silver Scent", brand: "Jacques Bogart", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Flor de laranjeira", "Limão", "Fava Tonka"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um perfume contrastante, fresco e quente, moderno e clássico." },
  { id: 59, slug: "ted-lapidus", name: "Ted Lapidus", brand: "Ted Lapidus", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Abacaxi", "Lavanda", "Patchouli"], rating: 4.7, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Um clássico poderoso e marcante da perfumaria masculina." },
  { id: 60, slug: "the-blend", name: "The Blend", brand: "O Boticário", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Canela", "Pimenta Preta", "Cravo"], rating: 4.8, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância amadeirada especiada que é um verdadeiro convite ao inesperado." },
  { id: 61, slug: "y", name: "Y", brand: "Yves Saint Laurent", gender: "Masculino", category: "Amadeirado", price: 80, notes: ["Sálvia", "Gerânio", "Madeira de âmbar"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Para o homem criativo, sonhador e realizado. A fragrância da nova geração." },
  { id: 62, slug: "good-girl", name: "Good Girl", brand: "Carolina Herrera", gender: "Feminino", category: "Oriental Floral", price: 80, notes: ["Amêndoa", "Café", "Jasmim Sambac", "Fava Tonka", "Cacau"], rating: 4.9, image: "https://i.imgur.com/WDpriz2.jpeg", description: "Uma fragrância ousada e sofisticada, inspirada na dualidade da mulher moderna. Audaciosamente sexy e elegante, para a mulher que celebra sua feminilidade." }
];

export const NAV_LINKS = [
    { name: "Home", page: "home" },
    { name: "Catálogo", page: "products" },
    { name: "Coleção Árabe", page: "collection", param: "colecao_arabe" },
    { name: "Contato", page: "home" },
];